spring:
  application:
    name: money-manager

  datasource:
    # Postgres specific driver and URL
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        # Helps Hibernate optimize queries specifically for Postgres
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # --- MOVE THIS OUT OF JPA ---

  mail:
      host: smtp-relay.brevo.com
      port: 465
      username: ${BREVO_USERNAME}
      password: ${BREVO_PASSWORD}
      properties:
        mail:
          debug: true
          smtp:
            auth: true
            ssl:
              enable: true
              socketFactory:
                port: 465
                class: javax.net.ssl.SSLSocketFactory
                fallback: false
            connectiontimeout: 10000
            timeout: 10000
            writetimeout: 10000
            starttls:
              enable: true
              required: true
            fromEmail: ${BREVO_FROM_EMAIL}

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api/v1
jwt:
    secretKey: ${JWT_SECRET_KEY}

money.manager.frontend.url: ${FRONT_END_URL}
app.activation.url: ${BACKEND_URL}
brevo_api_key: ${BREVO_API_KEY}
brevo_from_email: ${BREVO_FROM_EMAIL}